### ISSUE TITLE
Feature: render `require-dbt-version` for each package

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/hub.getdbt.com#165]
Rather than write in the README that "this package is compatible with dbt X", it would be cool if this got auto-populated from the `dbt_project.yml` file.

In the future when (ok, if) we complete [this issue](https://github.com/fishtown-analytics/dbt/issues/1471), we could also list the database compatibility.

**Comment by jtcohen6** [comment]
This remains a good idea, and I think we should take it one step further (as discussed in product office hours): based on the dbt version when running `dbt deps`, the Hub site should check the dbt version boundaries of all dependencies when finding the best candidate for installation. I believe this would enable us to remove the defensive upper-version boundaries that non-utils packages have against dbt-utils.

**Comment by joellabes** [comment]
Just came to open this same issue, as a community member wasn’t sure how to get dbt utils going for dbt 0.17.1 [(Slack link)](https://getdbt.slack.com/archives/CJARVS0RY/p1610369568361600)

**Comment by joellabes** [comment]
Reopening this - the _data_ is there, but it's not rendered on the page anywhere yet as far as I can tell.
