### ISSUE TITLE
Request: Make Package Names Alphabetical

### ISSUE THREAD

**Issue by fivetran-jacklowery** [dbt-labs/hub.getdbt.com#1675]
Convenience

**Comment by dbeatty10** [comment]
Hi @fivetran-jacklowery 👋  Sorry about the delayed response!

Could you describe in more detail what you are proposing? Could you describe what you are experiencing now and how your proposal would be different?

**Comment by fivetran-jacklowery** [comment]
Sure thing @dbeatty10 ! 

I often link to our package hub here (https://hub.getdbt.com/fivetran/) and the packages seem to be in random order or perhaps ordered by creation date. I was curious if these packages would be able to be listed alphabetically, to better navigate to packages of interest.

**Comment by dbeatty10** [comment]
Great suggestion @fivetran-jacklowery 💡 

Here's how an alphabetized version looks:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/44704949/181866095-e8106e16-1da1-4ede-99fd-58c0b49c7b45.png">

**Comment by fivetran-jacklowery** [comment]
That looks fantastic!
