### ISSUE TITLE
Remove the link to the dbt Core GitHub site at the top of the page

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/hub.getdbt.com#1724]
Carry over from #1719 
![image](https://user-images.githubusercontent.com/7335046/181620703-3fa0bb60-73e1-4327-8b46-609daca8960f.png)
The GitHub button here actually points to dbt Core's GH page, not the package as I'd expect. 

There is already a `View on GitHub` text link inline which goes to the repo's page. I think that's a reasonable location, and don't think we need two buttons that go to the same destination so I'd be OK removing the teal "⭐ GitHub" button altogether.

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/hub.getdbt.com/pull/1801
