### ISSUE TITLE
Research necessity of `www.getdbt.com` submodule

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/hub.getdbt.com#1774]
## Problem
@pdebelak noted [here](https://getdbt.slack.com/archives/CU4MRJ7QB/p1660656935969239?thread_ts=1660606689.336469&cid=CU4MRJ7QB) that there's a private submodule currently listed in the [contributing instructions for hub.getdbt.com](https://github.com/dbt-labs/hub.getdbt.com/blob/24f0eb7aff841fdbf6418f68f9f7f4e13135047f/CONTRIBUTING.md#development) that is a blocker for building locally for any community members outside of the dbt-labs organization.

## Next actions to take
Determine if this submodule is still necessary or not:
- https://github.com/dbt-labs/hub.getdbt.com/blob/24f0eb7aff841fdbf6418f68f9f7f4e13135047f/.gitmodules#L3

If not, then:

- [ ] remove it from `.gitmodules`
- [ ] remove it from any instructions (like [here](https://github.com/dbt-labs/hub.getdbt.com/blob/24f0eb7aff841fdbf6418f68f9f7f4e13135047f/CONTRIBUTING.md#development))

**Comment by b-per** [comment]
It is required today 😄 . Many stylesheets come from this repo. Without pulling from it the CSS breaks.

**Comment by dbeatty10** [comment]
Thank you @b-per!
