### ISSUE TITLE
Fix Dockerfile

### ISSUE THREAD

**Issue by seub** [dbt-labs/hub.getdbt.com#2386]
## Bug description

When trying `docker-compose build`, I get the error
```docker
ERROR: Service 'web' failed to build : When using COPY with more than one source file, the destination must be a directory and end with a /
```
For info, I'm using docker 20.10.7.

## Proposed solution

This error can easily be fixed: in the Dockerfile, [this line](https://github.com/dbt-labs/hub.getdbt.com/blob/2cec993519a4d340cdc0c8394e6dc5abcc0a9ec4/Dockerfile#L5)
```docker
COPY Gemfile* .
```
should be replaced by:
```docker
COPY Gemfile* ./
```

## Pull request

https://github.com/dbt-labs/hub.getdbt.com/pull/2387

**Comment by bbrewington** [comment]
@dbeatty10 heads up, the associated PR was merged - this issue can be closed

(it didn't say one of the keywords fixes/closes/... in the description, so wasn't auto-linked)

**Comment by dbeatty10** [comment]
Thank you @bbrewington !

Closing as resolved by https://github.com/dbt-labs/hub.getdbt.com/pull/2387
