### ISSUE TITLE
Saras-Daton/Shopify and Saras-Daton/shopify cause issues on case-insensitive filesystems (like Mac APFS)

### ISSUE THREAD

**Issue by NicWagenaar** [dbt-labs/hub.getdbt.com#2492]
In the Saras-Daton package directory, there exist two shopify packages—one capitalized `Shopify` and one all lowercase `shopify`: https://github.com/dbt-labs/hub.getdbt.com/tree/master/data/packages/Saras-Daton

This causes issues when cloning the repo onto a machine with a case-insensitive filesystem like MacOS (APFS). It looks like the capitalized version is the one still under development, while the all lowercase version is stale. The latest version of hubcap/hub.json confirms that: https://github.com/dbt-labs/hubcap/blob/main/hub.json#L304

Can we remove the all lowercase version of the shopify package from the Saras-Daton directory?

**Comment by cmcarthur** [comment]
hey @NicWagenaar -- looks like this was resolved with https://github.com/dbt-labs/hub.getdbt.com/pull/2628/files! I'm going to close but feel free to re-open if this is still causing you problems. thanks 🙏
