### ISSUE TITLE
New release is still not showing on the package hub

### ISSUE THREAD

**Issue by sarah-tuva** [dbt-labs/hub.getdbt.com#2740]
The latest release for The Tuva Project package is `0.5.6`, released last Friday. dbt Hub is still showing `0.5.5` as the latest version and dbt deps is not installing `0.5.6` either.

https://github.com/tuva-health/the_tuva_project/releases
https://hub.getdbt.com/tuva-health/the_tuva_project/latest/

**Comment by joellabes** [comment]
This should be fixed now! sorry about that

**Comment by sarah-tuva** [comment]
Awesome, thanks @joellabes!
