### ISSUE TITLE
dbt-expectations out of date

### ISSUE THREAD

**Issue by mirosval** [dbt-labs/hub.getdbt.com#755]
Hello, I'm not sure if this is the right place to report this, but [dbt-expectations](https://github.com/calogica/dbt-expectations/releases/tag/0.4.1) has been updated to `0.4.1` but the change has not been reflected here: https://hub.getdbt.com/calogica/dbt_expectations/latest/

**Comment by annafil** [comment]
You're in the right place! 🙇‍♀️  Sorry for the lag. We're tracking the work to resolve this [here](https://github.com/dbt-labs/hubcap/pull/54), now that we've figured out [what's going on ](https://github.com/dbt-labs/hubcap/issues/53):) 

Working on getting you to 💚 !

**Comment by annafil** [comment]
This has been manually bumped, but leaving this issue open until we push the underlying fixes to Hubcap :)

**Comment by edbizarro** [comment]
I saw that version `0.4.2` it's out now but not in the hub and it's feels like this is the right place to post

**Comment by edbizarro** [comment]
Hi all! any chance to bump manually to v0.4.2? Thanks!

**Comment by VersusFacit** [comment]
Heya @edbizarro. We actually merged in this new version I think back on Thursday. Feel free to use `dbt deps` with `0.4.2` right now if you aren't already. I just retested on my local machine it's working :) 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/67295367/132385297-49a3ba0a-29dd-473b-b7e1-7752c7a598fa.png">
