### ISSUE TITLE
Renaming a package repo breaks ability of existing package users to see updates

### ISSUE THREAD

**Issue by annafil** [dbt-labs/hub.getdbt.com#810]
### The problem

Renaming a repository that houses a dbt package results in multiple copies of said package on the Hub. 

#### Exhibit A: `dbt-utils` 

<details> 

A couple of years ago, the (then) Fishtown team moved away from `-` to `_` in package names. This created two copies of dbt-utils: 
- `fishtown-analytics/dbt-utils` [[link](https://github.com/dbt-labs/hub.getdbt.com/blob/master/data/packages/fishtown-analytics/dbt-utils/index.json)]; and 
- `fishtown-analytics/dbt_utils` [[link](https://github.com/dbt-labs/hub.getdbt.com/blob/master/data/packages/fishtown-analytics/dbt_utils/index.json)]

Hubcap continued automatically updating the latest version of the package, but _only for `dbt_utils`_ -- the new package name. 

In July, we switched over the `fishtown-analytics` repository to `dbt-labs` as part of the brand launch. This created a _third_ copy of `dbt_utils` under the `dbt-labs` folder: 
- `dbt-labs/dbt_utils` [[link]](https://github.com/dbt-labs/hub.getdbt.com/blob/master/data/packages/dbt-labs/dbt_utils/index.json) 

**This is now the only version of the package that is being updated by Hubcap when new versions are released**. 

</details> 

### User impact

Pretty soon, more and more folks on the older copies of this package are going to start running into compatibility issues, like [this one](https://getdbt.slack.com/archives/CBSQTAPLG/p1629228811408300). We're already getting customer reports about this as well as Community feedback. 

80% of packages installed after the fishtown-analytics -> dbt-labs cutover still use the old package name, which means they aren't able to see the upgrade path for dbt-utils 0.7.1. 

<img width="546" alt="Screen Shot 2021-08-18 at 2 14 18 PM" src="https://user-images.githubusercontent.com/7892219/129973157-fbacff5b-c063-4a40-82d7-6c6c90acf00a.png">

❗ This affects not only dbt-utils but any other package that has ever been renamed, including all fishtown-analytics packages and packages from partners and the community that were created before Jul 1st.❗

### Things I've tried

I've tried simply using [symlinks to point to the new location of the packages](https://github.com/dbt-labs/hub.getdbt.com/pull/808), but this doesn't pass registry checks in Core. 

### Resolution

1. Short term: we should work on removing FA packages from search results and clearly mark packages as deprecated in their descriptions. @annafil will run point on this one 

2. Long term: after chatting with @drewbanin, sounds like we need to take a few steps back and create a process for deprecating and renaming packages on the Hub. Ideally said process allows us to give a warning message to users about upgrading/removing a dependency when they run dbt deps, i.e. "hey you're using an old version of this package -- it is now called [myfancynamehere/myfancypackage]". @jtcohen6 and @leahwicz let's chat more about working through this one together! :)

**Comment by jtcohen6** [comment]
I'm excited to talk more about this later today! Providing a better warning system feels really, really important, and doing it in a way that doesn't hard-code the `fishtown-analytics` &rarr; `dbt-labs` name change. It's not the last time we'll see a package renamed and need an aliasing/warning mechanism.

> 80% of packages installed after the fishtown-analytics -> dbt-labs cutover still use the old package name, which means they aren't able to see the upgrade path for dbt-utils 0.7.1.

This is _likely_ to be a reflection of the number of projects that have upgraded to dbt >= v0.20.0, given that older package versions (compatible with older versions of dbt) pinned their dependency on `fishtown-analytics/dbt_utils` explicitly. So if you're using dbt v0.19.1 and, say, the `audit_helper` package, you'd have to keep using the `fishtown-analytics` namespace until you get around to upgrading.
