### ISSUE TITLE
Snowflake spend is out of date

### ISSUE THREAD

**Issue by annafil** [dbt-labs/hub.getdbt.com#831]
https://github.com/gitlabhq/snowflake_spend is a mirror of the GitLab Data team's https://gitlab.com/gitlab-data/snowflake_spend package. 

Hub indexes the package version that lives on GitHub but it is significantly out of date from the GitLab hosted version, and depending on it will result in duplicate package errors. 

Resolution options: 
- make sure mirroring across the GitLab and GitHub versions of the package is set up and working correctly (effort size: small) 
- rewrite hubcap to support GitLab hosted repositories (effort size: large) 
- implement dbt Core redirects such that fishtown-analytics/dbt_utils and dbt-labs/dbt_utils dependencies resolve to the same location, thereby not triggering the error (effort size: megium to large)

**Comment by dbeatty10** [comment]
Folks at GitLab are discussing the details and timing of option 1 here:
https://gitlab.com/gitlab-data/snowflake_spend/-/issues/16

**Comment by dbeatty10** [comment]
Resolved: https://gitlab.com/gitlab-data/snowflake_spend/-/issues/16#note_994443477
